#index:
#   path: /
#   controller: App\Controller\DefaultController::index

hello_the_world:
     path:       /hello-world
     controller: App\Controller\AdvertController::index

goodbye_the_world:
     path:       /goodbye-world
     controller: App\Controller\AdvertController::index2